import Head from 'next/head';

const styles = {
  section: 'flex justify-center items-center',
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Gamja-log</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className={styles.section}>
        <h1>Gamja-log</h1>
        <p>개발자의 개인 블로그입니다.</p>
      </section>
    </>
  );
}
